services:
  api:
    image: telegbot/tgmsg:1.2
    network_mode: host
    working_dir: /telegbot.org
    volumes:
      - ./:/telegbot.org
    ports:
      - "9503:9503"
    tty: true 
    # privileged: true
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # init: true
    # restart: unless-stopped
    # ports:
    #   - "9504:9504"
    # volumes:
    #   - ./:/app-host-link
    # working_dir: /app-host-link
    # depends_on:
    #   - mysql
    # environment:
    #   WAIT_HOSTS: mysql:3306
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "2"
    command:
      - /bin/bash
      - -c
      - |  
        RUN chmod +x /usr/local/bin/docker-compose-wait
        sh work.sh 
    # command:
    #   - "-s=users/*"  
    
 