#!/bin/sh

SCRIPT=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "$SCRIPT")
cd "$SCRIPT_DIR"
 
dockerv=$(docker -v)
current_time=$(date +"%Y-%m-%d %H:%M:%S") 

 

if [[ $dockerv != *"version"* ]]; then 
    echo -e "\n$current_time | \033[41;33m系统未安装Docker环境,请点击宝塔面板菜单》Docker 提示未安装 - 点击安装 \033[0m"
    echo -e "$current_time | \033[0;34m如果菜单栏没有看到Docker (新版宝塔面板菜单默认隐藏了Docker)\033[0m "
    echo -e "$current_time | \033[0;34m请点击：面板设置 > 面板菜单栏隐藏 - 设置菜单栏显示Docker\033[0m\n"
    exit
fi 
 


docker=$(docker ps) 
if [[ $docker == *"telegbot/tgmsg"* ]]; then  
    echo -e "$current_time | \033[1;31m项目运行中,开始停止项目... \033[0m"  
    docker-compose stop   
fi  

 

if [ "$1" == "-d" ]; then
    echo -e "$current_time | \033[1;32m开始启动项目...\033[0m "  
    docker-compose up -d 
    echo -e "$current_time | \033[1;33m项目启动完成！启动模式：后台模式 (终端将不会显示任何日志信息)\033[0m "  
else 
    echo -e "$current_time | \033[1;32m开始启动项目...【启动模式：调试模式 - 用于开发部署调试显示所有日志信息】\033[0m"
    docker-compose up 
fi 
 
 